service: keyakizaka46-rss

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-northeast-1
  memorySize: 1024
  timeout: 10

plugins:
  - serverless-webpack

functions:
  webhook:
    name: atom
    handler: handler.atom
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http: GET atom
