service: keyakizaka46-rss

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ap-northeast-1
  memorySize: 256
  timeout: 10

plugins:
  - serverless-webpack

custom:
  webpack:
    excludeFiles: src/**/*.test.ts

functions:
  atom:
    handler: src/handler.atom
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http: GET atom
