service: keyakizaka46-rss

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: ap-northeast-1
  memorySize: 300
  timeout: 10

plugins:
  - serverless-webpack

functions:
  atom:
    handler: handler.atom
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http: GET atom
